apiVersion: v1
kind: Service
metadata:
  name: {{ include "disk-usage-exporter.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "disk-usage-exporter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: {{ .Values.app.port }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "disk-usage-exporter.selectorLabels" . | nindent 4 }}
