{{- if .Values.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-exporter-credentials
  namespace: monitoring
  labels:
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/component: monitoring
spec:
  encryptedData:
    DATA_SOURCE_NAME: {{ .Values.sealedSecret.encryptedData.DATA_SOURCE_NAME | quote }}
  template:
    type: Opaque
    metadata:
      name: postgres-exporter-credentials
      namespace: monitoring
      labels:
        app.kubernetes.io/name: postgres-exporter
        app.kubernetes.io/component: monitoring
{{- end }}
