apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard-home
  namespace: argocd
  labels:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/component: networking
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.gabe565.com
    targetRevision: 0.3.25
    chart: adguard-home
    helm:
      values: |
        env:
          TZ: "Europe/Paris"

        # Configuration DNS rewrites
        config: |
          filtering:
            rewrites:
              - domain: "adguard.home"
                answer: "192.168.1.102"
              - domain: "homepage.home"
                answer: "192.168.1.102"
              - domain: "valhafin.home"
                answer: "192.168.1.102"

        service:
          main:
            type: ClusterIP
            ports:
              http:
                port: 3000
          dns-tcp:
            enabled: true
            type: LoadBalancer
            ports:
              dns-tcp:
                enabled: true
                port: 53
                protocol: TCP
          dns-udp:
            enabled: true
            type: LoadBalancer
            ports:
              dns-udp:
                enabled: true
                port: 53
                protocol: UDP

        ingress:
          main:
            enabled: true
            hosts:
              - host: adguard.home
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      name: adguard-home
                      port: 3000

        persistence:
          config:
            enabled: true
            size: 1Gi
            storageClass: "local-path"
            accessMode: ReadWriteOnce
          data:
            enabled: true
            size: 5Gi
            storageClass: "local-path"
            accessMode: ReadWriteOnce
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m