---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter
  namespace: argocd
  labels:
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/component: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: "11.13.0"
      chart: prometheus-blackbox-exporter
      helm:
        valueFiles:
          - $values/helm/blackbox-exporter/values.yaml
    - repoURL: https://github.com/Thybaau/homelab-cluster.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
