---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: system-upgrade
  namespace: system-upgrade
  labels:
    app.kubernetes.io/name: system-upgrade-controller
    app.kubernetes.io/managed-by: Helm
