---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook-urls
  namespace: monitoring
  labels:
    app.kubernetes.io/name: discord-webhook-urls
    app.kubernetes.io/component: alerting
spec:
  encryptedData:
    discord-monitoring-webhook-url: AgB/iLJCvadRSdzjSfSFJQwo+WOB/ItXwBmvXJv45jgb1+eUNPvb85wnCXEWbZzGsnnN1nXKI6mdmxS8RHmhyTQKH0G61k1pgnG2NutYK+9mdRbH/gCjHz1GwUPdu2X0k6/TmlSQzXlujYdINS7/rLIrudckWXetzwmlNmNq/GXUBXDgH7Ch9QiNjzOckyyVY1t9UNVODCcvBdNlBx3oZy7tZ18iePT04XScwFoDk25hVV4HyGGaoamdkCPy/vi43/Ttpo08GfKowt6wgxRtZW+HQekq9XpoAsibzjaVRqa6XKEtWk4eMDjlTtsCGd3MvgHn1KTamFj7djC+CJ3b0J2Cq7yft8Gh65IfgiFflTBMYeZa08HDG3dZOOsEId6r5llnVoss2ZYalRbRMQMmgV/e8Y0dJjmMKczlo82DusmbERvy2617xymClLrqOj6Y9G0LuSk/WSCSkIWYfePYHO2pevyafqI/ShbO2nXoPMNrUXsbcrhiWA34uBpwZfc/r6wB8GVVMWjHU7A1O3PXwhLBiGyj4XSzQhzv2FHHLuKsADi8gW4xKJIkoE4BBqN1jbrCOWl7VbXp7FbG2eLKmpK4UbcHJ1EYXzGJrQrQ/w1bw6bw+yXgxLsym/PrRRI5clBR437y6wTHp3ahY2aEq8W2K2GS9yzYaMHxnHx6edbYqoMTxgQSK7UOYbhyASKNRcn/QnIdOnXfq4eL0U5F0hiCHMqNdsZfURHg0X1A0qUZJkGfkNVwBhTLkmiq/VfRSk/9lnrvTutaAfNyul/fGEI/F6EFbVxMcs2m0upsxYAT0NvBT1YSVdrkbHiEzjQoAQHDyoWPluw0NKUL4MY0os2lS3QeGNqRgvOw
    discord-critical-webhook-url: AgAv3FQgQNPyoBxXQJh1XASLi3GQea9+N4rxJIUJNI0Jk92yC/BH73atJwAYIzRu2djC6Vjw12P963VVNvoXyGDdkKD76dw/4scen5hZTbs4K+8LFwY/y1ZhmBVnCGxOEIo206PGjJLCaPnlSJm0KwuucWkFlzzci+inB4LyYwEvzy3CxZaQPAkyKf2uAiWVh6bU7u9x4Fq9KOv4JFzHvWLIOfubWTSojxAg0PO4sfllT3CBkQ9qvcbHVAELgVJmX4r6Rx/8jdpxJq+bTrhYrkWbH0ybBrw3mDPt1Dl9EOTKCoJIPcVvUmxD16+nvhLkECxky1/h88d0BMZpT69jSmtVdFDtnorQcdD8D/co9VJCQ1c5Ue/3Ie7uuHDu/yrT8RI8foUf+KsjkrxA8ze9V3a9qowhUm32pKdaQZ9bOiAINTKAxnZpnJs2qAVLIWp+4aHRbEOY+XjXnHPB1Y3/0GXPYoab1Osa7w1DKLQqfmMzldnbaTsur8IAJPMsZeXKLimR3tcm6NmMCWcp90d1UjCVaMJCANGi/ATV0UoHzxz3AfRGkdDejyWKMxVAFT1Cgw/Ap/SOaP+Sxl4L+XApesFnNnxeic0H0YLGebtpZnHY4LPADSNJizbd5gQi6bUVqofkO9EnfB9+DSvgV+U1BDe47gzh0vfQKOFxRX4mgOUExXGfYlX37tnyHpUe13m/WrCF9xRk63wGiuJv+XWEAYA09d2xPLBDWpWEqmLBW1LGFrWJkAshDEa41Vj80UeIio9cfbWVSq5KS3sirPwVIOD0wxzVcedve9btIi13T3dDgl75VpLiLUEJT7Br/Qs8dRYCOyiC+rShMj2pxQYzJ5BtT5lEy5EA9hzO
  template:
    metadata:
      name: discord-webhook-urls
      namespace: monitoring
      labels:
        app.kubernetes.io/name: discord-webhook-urls
        app.kubernetes.io/component: alerting
    type: Opaque
