---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook-urls
  namespace: monitoring
  labels:
    app.kubernetes.io/name: discord-webhook-urls
    app.kubernetes.io/component: alerting
spec:
  encryptedData:
    discord-monitoring-webhook-url: AgA3sdP7QDgCONJlNtfKIdJRMyQTVby66GKb8bUsq2ALnOWMFDjvN3wpYEfQFX3PZbG/eR7g/TBmRavYong7pLnlAkU2q06Cue5ntNniPPuM+YOVgnlCR6KkwPRTXoVffaa9zMBFDqJcI+o55+SZvI86F9J46dj8ECsveGo/Je/eBkp9ZSrze5bIyWmqB8XVz84mi3SMbIbqx42VVYZ6r2PZcbjJvh3KVz6C/d6nOfGvf4IFehg/e0+1+kmKUIdZ7ifXz0HnOAmaDpz1Z9InwcMTVBvetkR4spINX94qr+nfjtvFW9CldjB04K6OwyLazuY/NAUyhCciizuKzPSpwQXNhfgc7NwmfNEQv0ewFk8UpLsbf28krDG0cQh3REhW+HEzXGq9wFoMLfDQbHx7sE5+88W4DNog52CAmHdJtoW+G5GRWAvfjCfZjks/axux93rX3E3Xt4PgcTYOTSVsYU/eS9CLmWzFJN2rgvqr7u8dQ6oUIOCqBPBM9L4Kj+1675UBLHDgRhhgk1EArwV2TL4r72m++qpKcps/lt8DJ+0NvUdAtL9bPZzaMHWV933KUuF14BkpJnDZgwy5Pygmq/fWTbE9wd6too/nzjBo2lY9Pd8ay4GDJYLHwndacPnmYrRn0ecYXgxWvyDAhAwFy1/so43Msggft3kxcAyAItpqbodV8oXOPCZOiDW+BgLcimSDpyeArv0y7nqKaXjWHPVQ6ZI9HWu7Q9WivdiZ/mq0oa6zWSRzL07j/fUf3P+7FTwFxlWV+uV2u1B8t+zn/uKq1PT3Q/v3jEVnEIeohuR4JVuaIOO0wtsQzRza1YeaOAwUDJDYJ9kJGu0NTCHTW9tuBz3XLU+Ghi9mjScsjFLu
    discord-critical-webhook-url: AgCDEKGtbXNcp3b6RuDdn3KdbP7gAjAY0Qtdu3o9UtTe5fKJ1I3z73/2bZRbDCmCeig4JYATnGHpDZO2hJVdEPDfuWJVEU6G/r5zuLy8fLW9giHhv8LkXNvh9JXf2NODnqGP5NkxiTOyKu/zQP1W2Fk5zsgU9gTh66mUhZsYERwOBcm/f1+qEMzPtWisNxqSwASByZL8yT9hLVsyYBvZg0YlCTgjgMnzbNtQS/dZlHhfIC9xYlMtaBGll9Yt2n2A2p3lFOakiI2ukZoN2ZzEReSMcjuQEKUXavhX1AfiYmyVoehqF4Vzn3sC4uRuwekZfCh+xltu2bfvS3X2kFKqAwFv5jJ3s9zfhb+6FJpQ2FivIhM1+r8ywkvCGS2oXHs4uHX82iTUFlSe37EDxX1d7Z71oNZhfQgOo31iX4buRoL/9ONq0ddlPxX8qdFBEKAps6ZPhkQ7SCNCWKMZU46y9WVtrmbhxrt61poWRFDBZG1Yo2xpqn0IdZeFENbf98ffPuN3AY5nV/jB99OCpXVojGKRqfG0eGfr710EdzLWTK1jKlIYXpGSaKbZCcYr42HJO+Z/a8kq0lFLB5jmhBGWSIrLVaq3i08429JnBnzD+2KtIsSlzEq8J7ngs4CsHcDa2KGzgWQIUUzeVSRBEyUq3G9stsFhCtyA0S8kJ158B850Nssm7X5bsJMaGrUx1PkVAZZEn6OJ1D3EKXqoJUZgzWw641ZS6Mbkax6zYYJ4IuvVCcIdLPPBSedJJCNYKRpzpBNTlD5C7ZqwUG1jtQltAVxPZATogbOlCqIQbNdxcc50qdbM0TZSINcvKDkOaotWZ5mS4zi5n7W6v2UIPvJnIYH6/kD1uVe9B+MNQyt5chxb
  template:
    metadata:
      name: discord-webhook-urls
      namespace: monitoring
      labels:
        app.kubernetes.io/name: discord-webhook-urls
        app.kubernetes.io/component: alerting
    type: Opaque
