---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCG73TfEcYYPBmMFB5w0VUCX5h3Gupn4/zH1YkPf6tKM3PFS13UCB4Fjp0QjTqP8sXIsbLYgFgOEG9ROssXVF+UQICUWdPQ1XwDGAiO3d7yW6vEzANYGaLXgQSN35BbRovM3GbsARJRPgicRpSWR++egTXLdrP+gPdxZ1yrl1U4mwOHOo7hRQniadeUUHSCkbBNo70e69cWkxSi9PsFSspwcTgvT+at3+H8fHtTRRvanhBSfLdSq/N3WlZCwA9TVodz2vJ5ed4WptqDnVZ1YRoy5GEUbBwja1lDKo1q8q/FVrEkYUmaQ+Tcx41ecD3DgBzQaoyL5hMCCGysldxvN39KniCom7/H4MQvv91jZ3cZ1A9sbusMgCfSVuGc+jbI6zrKOa3lZHxkOce9CSaHGxuli5NNwoJ/iIgGIECrgV11agj4mMhZa221HigdQ9OeROaacFVd+pMvpThJ4UKcPQ4M0qCnmSuR6HfP0mmy2Q8bbLoIZ68O10rBzQIcxVnwbCANbC0kRBMK0FG0XNP5djYdBkMxQngtCRfK6PU2JbrPzCcAsHiBe43qzyJQvgSTC3nos9arHkyM83OyExg1XKef8ar+BPPP3+FZsJd+LadWYGB8I/sg4p2Wk1C7ECx0WHEQOVZV2CikQ5HwY2NqPsDl4Rjzj3UjA0rr/dLme+uLxMsS95nxZz3QHuNMkmiGLvdb5HwpXrfcIg==
    admin-user: AgBgOq9L/HaON3C9R1bg66y57hjQoPhoxsHEguKz59XuUmlASqmTCDeAx7dDyOx1mkMFstmMcZvaA3uqiyXrqPuAftiS5r0M8ai09t2LI29I2WaakBn5vlRq5BnSLH0HCLBVZgWP7KxFcPMryN1Twz9U6NAfhze1hVrq//pPSxldjeS15cxJJgtDPEHIwR8ueuZkrbvrPoh6aLzJOHeswSDdKgtkSf4/69UdPFJtPr5lfHbm4qfe+Y89VtI74Y/eHILK6CnTXCopPF6v62LZ7SAHxMnO0BI07qVbxFV5c5sFxU5V4KuB9lRXax8Rly4WAZFCY88Jcc2KryuMbksB4oPR1WVnHd1r9a/yxstMTFg+PGzaYNoax0O1lFtHZ8YfNEaRg7/GqTc9ovkea4P2AJFqmx1RP10qkC1Fs9zXiiG2bSdGzvt5O9t7fkF0kouGF76FeeMaspxJYs+A0wSqzE/2JOSyh0lX1CEMFzZTk8ybTvPCD15eNR1OS89ec47IGPRng6lV2OEiHYUFqsaF9s5dpe8j/SEspQw1Y7QefLdlUGZMQAN3l+pZOD84bij6sxWCDb/fJ6fK8so6XX8CmpAH3HesHRaQVTTzw3SoFc0geuKLUOjC80pEnK2gWiti95Daa5k99Ea95wf/eSTzB3S/hx0GTevfv/ModUuJdm2vxERBYKfV2/Cyiy9v0cxcH7VJ6pumVw==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
