apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudflare.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cloudflare.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "cloudflare.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudflare.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: cloudflared
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        args:
          - tunnel
          - --no-autoupdate
          - --metrics
          - 0.0.0.0:2000
          - run
          - --token
          - $(TUNNEL_TOKEN)
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "cloudflare.fullname" . }}-tunnel-token
              key: TUNNEL_TOKEN
        ports:
        - name: metrics
          containerPort: 2000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ready
            port: metrics
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: metrics
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: {{ .Values.app.resources.requests.cpu }}
            memory: {{ .Values.app.resources.requests.memory }}
          limits:
            cpu: {{ .Values.app.resources.limits.cpu }}
            memory: {{ .Values.app.resources.limits.memory }}
