{{- if .Values.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "cloudflare.fullname" . }}-tunnel-token
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cloudflare.labels" . | nindent 4 }}
spec:
  encryptedData:
    TUNNEL_TOKEN: {{ .Values.sealedSecret.encryptedData.TUNNEL_TOKEN | quote }}
  template:
    metadata:
      name: {{ include "cloudflare.fullname" . }}-tunnel-token
      namespace: {{ .Values.global.namespace }}
      labels:
        {{- include "cloudflare.labels" . | nindent 8 }}
{{- end }}
