{{- if .Values.tokenSecret.enabled -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ .Values.tokenSecret.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "jarod-rbac.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "jarod-rbac.serviceAccountName" . }}
{{- end }}
