---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-argocd
  namespace: homepage
spec:
  encryptedData:
    ARGOCD_TOKEN: AgAy5q7RNGoyd6Stie438+G6vrtPxaYSR20L6w84Cz8cWp3AW0jUw5iRKb1cTWgF/TokYkgTLpPNlWSChM4Jr128u/V/vmAWSvrNOrHSj/VrQjZ4exAJMqgnt4ROC+i3gzQcHW4/e9bEKlYGZ81mG/GGZ1/hBec3HAIWmCUfwkagJ+TAQVzX8esmt+UBmzdgp6lcl95gRQHroq0asHSrZm2lQ6nzrYZtU8KedFhMg7bnLG1yDoVnj5uqFzllfb8dWmpKfzgqKjdmBZUCS2UyIPTN9Kuwju7Gn6EcS4TkeomtQbkp3sTKzrPJf6fWKdnrgl5j65SYOmKE86H9aWfbp3gbPmj3DdnBcV0JCVnU843OSPEbcqYELUVlFQhdEPhqudWfBWKtH+OcBVrWeb9KgSd+sFEpeKNBWHxjC6F64mgUq7yH64xV7nSQymFXULrl9fP+wL3Jhwz6Q7qAmVGkPBuwuBlFAZNxXw+RrRzk0wwLEVKwVoCgQJmnfRegFSi3nGrYbdO6tTgtUm65KNUSuaFpkW8aPZJcppxJcb7iOuJUSqwEd1eaTSYMpzMhTqGiDpvnVjo0Vjeipd00Fm/Ido//HFq6luI0LBxhQbVlVjwH3mv55Hdc+Wx151ZO/6IP8qcQcOkqcWTDP4se/mAVzQpQ/yCjHeXBOZd1UxjazOjRDq+2TD/pCoTtOoHSHSJUt97yk3XXzD05NmScm+be6u008JokTLTj5rGjoTPN2CWKwo5JpMuGHeZnVVfFdT6lG71kEnHVzk1FSMCIe+jyFhUfMJva/2TK1kSQnNUXhtuVy2ED3VNaCISFZyErTvCdq1uEY6c9/OFCSeEOsX3kk6nLF4fMInzORv/qF8SLRG2kUJuuQmaWhfaiLiQqyC+x5t4LVTZODlrfI8Z9JlbrvimgCFM0mwkcSjC8ujPW3PYT4l6Jd4ERmyTfrWsJIxUlrwEn09++t6ZLFgwbbA==
  template:
    metadata:
      name: homepage-argocd
      namespace: homepage
