---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-argocd
  namespace: homepage
spec:
  encryptedData:
    ARGOCD_TOKEN: AgAXxs7RFXLV0J2j4Vv0RBGwJWpNuzqc/UAmfUCoSkCXFHJtmhRBOMtUdPVBllItq6BiusYWU+ng4/ePbLQ7QKaV1EDwFeTwDQCqxDeqQHuuB/D9Fw2KKAq9MB+bK/1H54n9mYiKGmHnMoEumli2RBLV70VbKxuomTk+tDQkloEC731x7B9zmbdWAMYHZW+mNCYQBqlLzifPo9GwJ6tVGHD7fzZLH5vxtVUJaaP/oevTw3YRcvItaJP1qa2cWZFDMZHZ+3uNjPwt+ZQGwlltW30Lnvm52NRfh4vr62OZVsJluOBUx+G99I/Y67KvUF+JvKHoJ9Abz3TTOYD+oE5XNCHUulSYEzg7z4KyXNiVQ+2tupKWBHmVnjzp6yXqDPDM1hTa4OUv++2Kw8lK62iudWb71UQcDx8pIV44NXGM3d1H3dOtFiD5995f5ATgTmtuu3y/CdPc/7B8zYwkJRorMxCD2Pwz8Cb9rWiw+lJTLcsUrMgPQVO9p9Cd4Lh1qMu5UFxbhPN/lvnxwOa936S4YBcPC3GvuP0wUFhzkA7vh8/9p69vMUdouxCDnZE/wtVCujhHK0TDn5zXwS55mhcQll4WDKnU2KdL5/XuyCB8Z/cHUPM8IjMDaI9jONwQmfyc6uQDZf+xyT0+EriQHz4kmrXe8angyO2mMCODxGgfq4WEJ1K1RrnvG50BMh9IYH+j0eosuXfc1n3+HthtbtOzMRMNSAad20dp9MLnNilY+l9OJM3hACjZJLTGoqtpzPYPWQJKf3S0iijcQcqVgVmMxv+8XTfzhH9PC2m4HP9eT6bX1bNAlxTEuNDURRzxfiOK/RQQwXIhnWCH3jhUAq2r3r37rStTxmi48Tv/w0ZCgcD36fVIXUmXyNfMY2ADmZLeoRJN1ReB3kYOM/9O3QmDWXkacBgTZVi/K/y5T/0soG+saYHgPtdS1zEwIyRHYer4DwTCCXYgWNqTd/OwBg==
  template:
    metadata:
      name: homepage-argocd
      namespace: homepage
    type: Opaque
