---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-argocd
  namespace: homepage
spec:
  encryptedData:
    ARGOCD_TOKEN: AgDtPy75mHBhSKhKSw3ESqam93E82R1sL2OdjAEN8N2m5U2bqmdee8hIwkVJZDRuoBFdVSzLIa+SXVKhQOyxlOx3x4tUUFvsxdq5It+wNWDMlEhr0+l49gTVmqbuQvlHpT/Cn5vi5Yn/jbMX7Fl58nhxQV9EmArCgILLjD1aVFu0htfWpaDpvNwOvaxSfPePHvdEEs47bmB3Iw5imOMVwLt9g+CsWb1n5yNNnfh75lknQp48VWMgRX2GD5DE4XGQ7FYouPeAbswjF7VV2R2Z4la4tCQx2pb/5lA9uBgW+jGNscAMYOZY5O5kq04iF+mg0ISg24bQWGT1lIsdd35Xumqi0oay/CibCUqohuX1llX1f4rrluKyQF+FfpGko1k5H1D4Z4/0RV/o4d8yIDbVDWI+BWl+w1BYLM2F/PTM8La93/StkPxAF4GkH+3gEUHwexLtg68GqPWNoKmSOkMpA9kR3UO/0KNOUDXCHhmmJAv+8mvug/JSPJmMZ15+nZC1vHxRj8goAPdFUd0zXbq0egLLzCwS3luGVwMHPxaW0vXYk7AaXTiIO6cj3w/T/L35v54Gf3Y40k44ZhFTkIA6LTaK9XvyrBvtMoNxRahdacjE38b+CWsSM82JBMynESOi7EApG6Sgy9ot+kSAeU8kSjyIu2FXPRfd2t+dDGXXhmUl3HPno1yby/9YhFLvEVpI4lE7k/lWQVMhbdjeN1bUNQEl
  template:
    metadata:
      name: homepage-argocd
      namespace: homepage
