---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-cloudflare
  namespace: homepage
spec:
  encryptedData:
    HOMEPAGE_VAR_CLOUDFLARE_TUNNEL_KEY: AgCBRU0YPZAw7+nt04RrhY7mGwjYaMMl6Zr5YhbOxEpXvicFeXxw+kWMPHrDgdf6paaZp0O9Dyyh+5l+VR7KhVdOkyyQVCHW/tG76t4WeFoXVej/zy2smqdNkQVgRtDjtNrK/DStkMo2ykBjVD6LOp2NQNM7dORsQ5P4hnqrEM/tgllYg/EEa/y96hg1/J11q8pIqk01zNt+VZfwlGQIhw68vFfZ65lYnNTfeQ+KbqqAevBxFSx+tFU/CJleGvItZ4W9xgjeYW8sJKFAWtq7WHACmAezEifUMg2iCnn/potZFKr84gxpLmjJWoQ2wdA9H/gsJ7mdyffvdU0Sp6rSeHMmpBuhAY893C4R0WkXFDkt5a95VJ0lMjr+knFrgFis+GO/Fs6Evg30qC0xoZyJp/077RGEWScrc3dRj+1QAdJSn01nHOlloBq1nalG0H1nRvS5aS6AxoZ4oWTwRBxzJEbGRuy6zbVYypF4I928GK0PmfrIRZ7s/FsdhqbGHgYqi4nkh5qpRqzdj0FNEnf8f6dHmCS8jsQAqgWhftG7yEopq8c5ZGwe/pfGd+g2TT+4eYGp/Ikl2dtlrUGxyCWNRKkMBnzPa+3eN52qZJBu0M9Rht1CspdARjBofEueCkeiS+9HzLdkp4tAEb+n8LfGzfLknFnqIqUccLfnYtHPTfBCxQiPF07sob17r85VaE/N0qNWgpQq0U4i1EN/hT37pe3K7ptJlM5Iavwo4WCFWeA6YjiYl4SJ86cjz7HGs8NkK7Yb1zOYIw==
  template:
    metadata:
      name: homepage-cloudflare
      namespace: homepage
    type: Opaque
