---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-grafana
  namespace: homepage
spec:
  encryptedData:
    GRAFANA_PASSWORD: AgA1O/nqOcCLAr5z0dDcgLCOhdUMuLyrxX0XuRO7Rb69TzDyYJiCW0vD9QwpR1KmuRxNg5Q+U2r2J46jothfqYeAWpmzWCPDrKm1HmXnwvu3KW6Tcu9Y/mP7OQsXv7ZV7PJuUnm+fDLUN2+9ki41GU88SOntoBxNiWXN6AM7U4TyKWpSMoojfnDYkYhG9q2MLlNX9xfOP4EtJVaPO5n1a5IOpH7rf/SkVgMiE76OLx2cHFYPjaEc1PtBZa4LWAaOxseBu0G5UwrIF/kyYgcuwyyQAh04vY5GQ8l2ho/G1OIfqzBTeSa5Szhpas4Suz9NB8xcAnfFw2jEwiGgJuAcjvRF65cL5iA4DgtvYpHDWlJUawPvNOWiZCtC42OFdk46Toi8cfH7bf6TviL9JuMf3M4oCAHQLNQaWMDgFNw2d0oGsUlnWrHFagyaem1h8k4Y9m63kDC7KEliE+u6aiVQp6CJmDB3DGoBniKGpYYmklybBtQaq6IvPO0u9vGCXTajYUXAY6zNlK7MUiUDy8gFXY8ELLnj21IzD+zlETRgvmqQbRVpynwYY6sZG+8Mje9GUCP8FRZQb08PechKO07b2SGGAL2A2bJ9qR69Hbk/NSIIb1c17V7e7hT05GmnI0cnTNxrI4JG1I6Ios0R1FLKYwJ44U9MRfkaIbimYdgGOXSDy5mL/OI0WM2xc2GUzgpCQt8dCrdTt5MtYw==
  template:
    metadata:
      name: homepage-grafana
      namespace: homepage
    type: Opaque
