---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-homeassistant
  namespace: homepage
spec:
  encryptedData:
    HOMEPAGE_VAR_HOMEASSISTANT_KEY: AgBSm9xeqCCFIb5dutdE3j3UMxAueFOfOeD/9SJNUNYOD/YQmPM5Ai85RqaxWX2fkrIyj4Fk1xgNSTK5l/QHay3/4x5qItGgKMVl0CmK+ZHGrhF3cF5ZVbX/FETNbxQt5FYrvU4ffbjbg5aVH6HBlKsax0f0vG6x9PrxyMFwoW1PRrWZXR1gZERCjNSuPaoqkaD3IQEU01hS/+NbaWU/CPBIpuBR8jheK8LQX1IyumTzVMpUIuR/QT8EuTT9VjaDPCkrZmI8t2K9n0Mrkd6ifZeZcXWhg8SrBHxn41SGuYyiugNjlX7uRaDH/M3GPJg1+yEnkt3XGNxchQ3ISmhkFnpG7+RELoX83lvZ/j9u/Ew064PQdWkVLLKZE6rFJTlrr7/Icoih4QC2OqNg89F45hEFsecFDDG012l4EoJy6ZeCqLwe+mV5N3ikOAt/sPCYX9m3yVhzL5uPsP59/dh1HHq3gyVLLIjdjmmQOia8Te5eTLqnp3tVM7FeM6eevEqpr/12p7T1Bin40Ix6xoYjWdaFVB3CEciVfOJLo4nnsjl3BdzA3riw2K6xyy+u5pIUAauF7e0IDkF/bjoyKMx471AwxXINyXjBthMDLFEhYtpk0/fiW7ZqoJqfhXvZkYnUNpc+E2Scee6QlJ1O7PdnZ7kDO6szK4uHu+SB25lMUWEV9p2Xzx1PIO1QbNSKHon8XLQ9Pie2fbVRZB1HKjYpQQNKX2tL4QHMIFox2a6E/h5DmH6btxsqh4GBAEsjrI+U1JM51NWCvgAtnkZ7PLt6CEJch0FPb8D3H9bLNmKcjEQ+MahqfWBPAJvc8cjMXCa2c5z2HwDQHfvaOgGztCDsmbUxLjujkq/iVMWJbUNSqSyiFbDcDJMeE5pQTbOlLya8DGewXVbko7ds28AtTrtoy+kYtDTUQgLQ0++0assEhljhi+JadqPFwAk=
  template:
    metadata:
      name: homepage-homeassistant
      namespace: homepage
    type: Opaque
