---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-proxmox
  namespace: homepage
spec:
  encryptedData:
    PROXMOX_TOKEN: AgAgHu1h60G/cvqKIMHoZMVdiViWwORd4QOyFqeNnnM1BL9XhkMCsyDDnAsFS7HraO9UfXHAmlJrelMOfFhauanFS+iqLOIkzQkMoCjC5H+IhkazeLB4d/IiksMC3pbCcyG/Gfjb6QUXM4BZrJFe67GlaDvfSs/ew/brGy5QbOhs9XaRDq4D/PvsPV6kneK0gz7CoH/VJ2n4egmLXL2xzfBY8sxaiJ76pq8LswoFEBQjGGojLN1uge4GTP3sIUUftGLDa4LST7Mwe9X3yOOaOI/PtOnOJWQi+yZUGYClp16PGhtMu/BuMRlMIRQspF/67WhJVVypbv1wcFADfvWOWnBlCPT+OzKGh7KZbP331ciEysxmk4CFQl87vMJTfk5mq5jq/Q53h498hxRXNHvvnSafRTrZOKToPljEGYSreGD56z85O+UYLi9MIdeHJIHVwTnZF/bNF7dfciACujMjKpnDIrqGUaYLQ2vL/+yXkIlYsPU4HmOeJb8U7XbNrYHAoGVEVwIXTNyNrfivgn6fh6SkysoWtVcL6hokfsCXMtiUEpHgQL21NGxfSzUyB41eHYz9DQpelcDgLF6fELz/UIdCyJ55wA3llOOuZUJM6sVhErVnROHPe5gZQcjrAOXk8D/vz8X9qd52VbGmfSJqo548UTtq1zc69kl7tiYZWqGIwu20uVklf2QX4DJHjvrycDCoj3EGPeJYJWcBU0kYCAC9wMGe+zB9VJehAo++bbk+as6OQAs=
    PROXMOX_USERNAME: AgBIGRN2xoTTC1VN69QywErF9BXfJVVfE8TtIUWnM+XFOU3yzp/Nk419PxX0S5BULhDWkLbSTh5SpwtmrSCGUPf08nnh3lM23YW7XeVsjBVtT+pW7JnspJKx8dYPAwTq6bNnKxxD6OTOjY+8o7XDvkuApySLsV/n8ZLA0gf9Lg/x/9hyeYqBdoiqNivxDTqAZvfRZT065mPNELmsc8IDMwEnAoQW9mU9rC2VsOCw9p07CZBn58QjE8t7ucmx+yuWbTSzhkikefRKpGvkQ+TR1r5j09s03YcaYNZQmYxgWY3FpU7n2e0il/hMu08XGJYLFMnvlsSzDM/6JSZlfUb2W36v7fuokoktb3CPU331Tq2YMWY3DQHFghOyyghcvixP2cQRGZMNx0XEQYcSXi7KiwkUf62M3RcPMX3aAUctfzUgXVxnBpW7wGB4S2fLL3v/uMaJv2101+CzG63998f5R5qtMYB2tjq0ZQ27OMOMh2SLGmP0p04QOfaAySYj2fQ61oxzfOEK7DeJeQsilDMICPLa5Eu84erwdOqEjKHFWWsQZpdtxIAX4EGervD4bNgSnsXyp8jsLo9TImceUr6M6CeNmlH/iFVvTzO0eoHpocH6MkbBZpoB8Zs+2cWZmoV2+U1jXPAvSPuG0h1Y0cdcbWZQNMDTlDQrNshSifm2zpjvJXlRsBB5z92YWx5anJWEWcIwyjM6QcJLzA4zRHKLE0JItw==
  template:
    metadata:
      name: homepage-proxmox
      namespace: homepage
    type: Opaque
