---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-tailscale
  namespace: homepage
spec:
  encryptedData:
    HOMEPAGE_VAR_TAILSCALE_KEY: AgC7tPPZyLqbnswPApTGXBZgcerdhi300WeAyHLkE2FRceIEPzpFym6YKv3eYzs7yVvl7WEWnS6eda9bejbDNr4kjHJtdeqIazdLfo0vOsHaN2u/UZeWLQRJEjKsMH4G54nAtMhRKBmQkWsVz2xCMEJUR2FtXhLd00dP4kkfr2QllocNxObt4Em58ko3l0K7P2acJd/pMNxp1L7iIRXwkxU2EvyyNoCe9QXhlD0lNhlNi4nzrePn+epZAvQoikRS/pE6xKPlefR26s0aYEDJkXqPToV6aQIAmxVvLHvb7K/5Mn0Bcgd7eQ7ApPfWSAWFyrC5yajpKEhYqw/nnoTBPzKKSuFGjWseQhLTdYZRVAgY6HZG7BN35LeNIlsiHtvndqZgeO/IEAWeW37aatsPKXBKuyuyAIDaVGB5K0DYzfE9ZZvqKMg96SYGPOXF+cI7fJEt7LAh1FCshuhQ6SPGPl3hiKxtfnxPkN4F5tyjUL1az4JXoJVZ6JGACfDu3gTVAWEQEDf6GsztSeFFA1iAbIdSeuIePiRFTWccPUkCVxaD2cZAFSUv1NbrsgzQ8/4Sh4VUWDCbJ99+QCNWIcMnSQhzU9AI3IjmtJVxyS3mfp3XEQUQrl1VXksOmJe0ZsKHrzry48uLeqOrFe0T3muu1xdrtXukDyQ/A9ZZ/6qDh3yCYvr+H+7G+uVFTt+Mn+ObZeWkZ10KTF86HstG3iMFihmFcNjl0dl/u/E+I7AbSYsz18Hoj8FQSshegZ08rh0WXUrsMUoYkev4NPOuJTNTZg==
  template:
    metadata:
      name: homepage-tailscale
      namespace: homepage
    type: Opaque
