---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-tailscale
  namespace: homepage
spec:
  encryptedData:
    HOMEPAGE_VAR_TAILSCALE_KEY: AgB8X7Y410SordQf8HTZj3he9mFX4c+4l45kxxPmulz02CUsO0/XLvXKy98Z66vjm+4bgZbgQ8sEgp90bsexE7DUmAhgcJKazOREwOWyp+P6lCoyjrgU0qgVYTm2KqLa6V1dTp5bvdumaXztXzLs8HQt/bhvvLcP0ZiOmsEAdn3d9TDWK12Po6Sfbfc72x3cp5alMKoWV5LnZLRVlXFsaai32jGsFP4hvjJmMgCi9xP/Gw7EwKd6OJytrkH3h5jh2vEPrJ8apOeYf13kThASPwFGSctLEfZHrXX9FTbKuV151YY0xUlomHdCQRCStA5F6wa7acxTUJCgZW69cU9Yl6NLMcfj9u6Dv7+Jnh9Z/2+QBnglQSdnZJG7zZVzcjm2W3zzC28LQU4w+VIwEVL4rprHV/s6VcyLIPEtwYTQsJYr7+UhZ7nw0jBrN0evALmm1E4xwGvAZxpUSl+1qsbEto0cQWH9a3b0324AyN1a5J/MJmiQXG3fNIRcILK1J5Or50aTG+QbLTIeqzGfc0/qEk3SUAlB8rNb5o2sCi6qjJqTgghz0UyL+4w9bGvA4Fwn6DFVkjdqcE8zM/tUUXBJ1ou5ELvboxiqIZLjIFUiLxkmATwyysig+N2KwyQftZ/i41uu8DY448E7wdEeK6cmS2+vIhZIS0BIYfMD7ar/lUJpJHmVZChnboIhNYzfcfoQ+98g3VII+O5EAA9z0kl/rlT3L4bLIei4qpevD/+9ph+onvkxsbYlfro+J+GzOKBRqGKtO9zywrdTrzmXZXE=
  template:
    metadata:
      name: homepage-tailscale
      namespace: homepage
    type: Opaque
