---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-tailscale
  namespace: homepage
spec:
  encryptedData:
    HOMEPAGE_VAR_TAILSCALE_KEY: AgBblshzneNroPbQlkkTG6begM8U1fiMnqBpFoqzupEIvDr9x+cMcmCc1B35+B/fgQAa3KJzy6lJzf6sCznTcJztvehWmAqRQMF1hQCa/PT4JjYIj4adLmhCVDGm1QqKwJKMxe2WAzgH0RCcbSg1AKHvw9E6XuwD65dBQg8EKOF6F7HOnI6PNrswr1VHqakUrADHXpHLLvO2rS89KFICkZiUYI4WbpuOCyG2ABJ3KYWJyKvUdh62glTDlaS1vKoueVDKIqH+qBa6yF6PpCRHh1CMyArYUczJrubMsjAGD4OyLxGNn/CG7dlgxiCA51AZVivV4ujIIICUb09aDbT/N/tUCLZi60EaefEr2T03TyFCNu2+a92NntxqrIMsEUo8u8cWqMVPUeqP05DiIZ0tdbDZmcOYf7+UPTDWCVF82i8MM87ACqbHeBwwW3OC1u6w/4OiJN/l18iJCaC8YMAdLsQrQMORlzU1mrjn4TZxU+mpU9Z4kN9IAgMKGWIRhs2MOECpuSmc7CGwpdEnBoJs5PcN7d1vlSQZgPJfExcBhPBLDuWRvXt0ox45Rizr8PHxG7ayYohP8XpbdrFcXY24VTII5QjbF2beFCsRv/N4QgZ3y1VwXm+O/HO/eQURmMmbOZbrdcvhpkujZUZsv4MZGrdt5hA3fQO9gFAtJGMIjfTWcS6knqAr1Xq7aZcUOuDnjSEdi2AG4xreOQFR+j1JMAwWcFFds5MwLRC7jmZpfJcNIh7MzwYYgyKKMpwrhedQ+rDmC8n1NayNKAN68DE=
  template:
    metadata:
      name: homepage-tailscale
      namespace: homepage
    type: Opaque
