---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-notifications-secret
    app.kubernetes.io/component: notifications
    app.kubernetes.io/part-of: argocd
spec:
  encryptedData:
    discord-webhook-url: AgAcksCP3c4Z6OlA3rD3oubFOq+rCvwVrYiPEvd9fA8bIeUgteWBU80++MQdAWRTgkyawEn1ux1ha8slz5B9N5HY+HtQ+ClsaV6OE1rWOsab+qmWmsVY39x1T5o5M/XQvnGSZBHJ7ORgzbSHV/ZxszV0CWiFbcauv8PiXTBhPqyjKzu/eu9I17tZhLBL89hgTyXbTf8HATcAk0ufqcM1ttIvN3CDBE306DB+BMtdNCK1nlQxBfpLRiWksGSSxAgYg65sTNakEm1T2w9DJGBTM5MAEqOFcJf9K+2tR2vszqvwu1fqqnwh+fkipJHYK0VwDe4aygI7nhKPsfZtaA6CxV3MLVEOfQ/HmPFhRIAY4h4+Cg/xoOR9fRGZYTFzHykT8Mx/vrebovrBr5AjdYjBrHbH1u2n14qRWZpwJfFsWdzaY5elo/Ij5ewuaXUrPzzuYHDJypzidMXaQEHhfGzSexG8Ai0xQNNPr4okMOHqUeAu2TOUS31dLqnPBLbpczF1Pb5hD9JMm4TknQOpcZy2nhvaGWRWfSCaRdcSY6Tty78EO4pXFV3IiDVukguHeJg7rgdro9Z4Pqw+T+8QUSG3bdFqyebegp/8KW9ta1bW0nxL2xQrSKBpEi8mCuKPM7volHU0tp9bQgIwlznnIlOWjIuANpP2+nTXFlhoam2CrK9klPT40X1fTw36M7HDRTXyKfLWHo+34DFT7ySe1OXe0HAq8YWZDCp5sm9GcJsEjkoVKN/UIDWwoqYfehwC7U//5ZIbu/TNF3HPRzoqRJ1gTO7U6tjDqB6gWfxqR0BHZMUNU4IsD3jE1KS7KmEAwPCEjywn6XlLT/zgaIBqpVWnWm/RHtKDn6taT1FW
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
      labels:
        app.kubernetes.io/name: argocd-notifications-secret
        app.kubernetes.io/component: notifications
        app.kubernetes.io/part-of: argocd
    type: Opaque
