---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kured-discord-webhook
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kured-discord-webhook
    app.kubernetes.io/component: notifications
    app.kubernetes.io/managed-by: Helm
spec:
  encryptedData:
    notify-url: AgAzSfzsRd849kBwYsSmuGVy42UDtbH6/FYnJ6xYI5Y0ICE2O/5TMAftXDiWW85h1UlFhUwtSpNwFsowMI6DVJZVf4ID7hBfGwCQWii3qqYJt44qTXjCWhBHeMkwakDP9/r9+KCIinxRoLH781B45Qv7wsoMpPKt3fw9X6+soXvgKLgocaTykhxSwCSsecSAUDp0PFpVWZBrxTsjhLPRhsJMj/Z4IWeCh6wexCmzIEIXX7e/lBoor3qiStGjrL+zBGETtQzashfHQ8hwtf3EKnyvc2w6DpO0ExrHXE+Rh6SNgzjN3Jt3ht4/lGiooLg0qdTfk9lJ5wn07BnYMyWEbJRP0sGkegntXNjfzBCdprTPLZF1086IPlYmxhLvOvzP7iC1KJ+bqulTqynGBFCJDjjCzSwtuS31Vdpd8bIJqJNsiflD9P5Du5RMPrv9YVol+213vVCLlupPXPyx6xCn/aLBeaY2qflab0vF2NgybTjwmXKmxnMux8itiSXZ7OmKbYZWTag2EwoFIyHMWhe0tZkUMuPdEFGmFeTPbTbF1VxKh61HSFJSnSBbPwBR5+/9Aau6e9xqbznXGBPJJYYwWZivYnD4g6M04H20GxWb2byUHHiP66e0S/nlX+tkzy/1nhK1qlAvrlh2+hF2CJCa+O1QhjVS7znYCNLKJKakCEedlurU3ncunzJX1SKSvy3HuMMoPbuKUnIVVEFwZ7oZ6gLmngaBxDoZhf2/4mLKfErrrKxjtdkZUedhrdZl41lYFrzOO/MRHtoxvN/PKDzw5V9F4mFsu4nBKMRQmMhGDuU5mSPKZIv8aK+I8cQEE3xDCyKkaw==
  template:
    metadata:
      name: kured-discord-webhook
      namespace: kube-system
      labels:
        app.kubernetes.io/name: kured-discord-webhook
        app.kubernetes.io/component: notifications
        app.kubernetes.io/managed-by: Helm
    type: Opaque
